version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio_server
    # Set the credentials for the admin user (API and Console access)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://127.0.0.1:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    restart: unless-stopped
    ports:
      - "5232:5232"
    volumes:
      - radicale_data:/data
      - ./config/radicale/config:/config/config:ro
      - ./config/radicale/users:/config/users:ro
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3141:3141"
    depends_on:
      - minio
      - radicale
  bun_backend:
    build: ./bun-backend
    container_name: bun_backend
    ports:
      - "6989:6989"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      CALDAV_URL: http://radicale:5232
      CALDAV_USER: ${CALDAV_USER}
      CALDAV_PASS: ${CALDAV_PASS}
    volumes:
      - ./bun-backend:/app
    tty: true
    stdin_open: true
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are what you expose to the public internet/LAN.
      - "80:80" # Public HTTP (for Let's Encrypt challenge)
      - "443:443" # Public HTTPS
      - "81:81" # NPM Admin Interface (change '81' to a random high port if you want to hide it)
    environment:
      # Use an internal SQLite database (stored in the data volume)
      - DB_SQLITE_FILE=/data/database.sqlite
      - DISABLE_IPV6=true # Recommended for simple home setups
    volumes:
      # These volumes store all your configuration, SSL certificates, and database.
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
volumes:
  radicale_data:
  minio_data:
